### ISSUE TITLE
nunjucks render error

### ISSUE THREAD

**Issue by lzq920** [tcrowe/generator-hexo-theme#14]
after I'm add  tags and categories pages
use the ‘hexo g’ command,An error occurred in the console！

```
    at Async._drainQueues (/Users/lixiansheng/Visual/blog/node_modules/bluebird/js/release/async.js:
143:10)
    at Immediate.Async.drainQueues (/Users/lixiansheng/Visual/blog/node_modules/bluebird/js/release/
async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

Unhandled rejection Template render error: (unknown path) [Line 10, Column 29]
  expected symbol, got pipe
    at Object.exports.prettifyError (/Users/lixiansheng/Visual/blog/node_modules/nunjucks/src/lib.js
:34:15)
    at new_cls.render (/Users/lixiansheng/Visual/blog/node_modules/nunjucks/src/environment.js:469:2
7)
    at new_cls.renderString (/Users/lixiansheng/Visual/blog/node_modules/nunjucks/src/environment.js
:327:21)
    at Hexo.renderer (/Users/lixiansheng/Visual/blog/node_modules/hexo-renderer-njks/index.js:16:14)
    at Hexo.tryCatcher (/Users/lixiansheng/Visual/blog/node_modules/bluebird/js/release/util.js:16:2
3)
    at Hexo.<anonymous> (/Users/lixiansheng/Visual/blog/node_modules/bluebird/js/release/method.js:1
5:34)
    at /Users/lixiansheng/Visual/blog/node_modules/hexo/lib/hexo/render.js:61:21
    at tryCatcher (/Users/lixiansheng/Visual/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/lixiansheng/Visual/blog/node_modules/bluebird/js/re
lease/promise.js:512:31)
    at Promise._settlePromise (/Users/lixiansheng/Visual/blog/node_modules/bluebird/js/release/promi
se.js:569:18)
    at Promise._settlePromiseCtx (/Users/lixiansheng/Visual/blog/node_modules/bluebird/js/release/pr
omise.js:606:10)
    at Async._drainQueue (/Users/lixiansheng/Visual/blog/node_modules/bluebird/js/release/async.js:1
38:12)
    at Async._drainQueues (/Users/lixiansheng/Visual/blog/node_modules/bluebird/js/release/async.js:
143:10)
    at Immediate.Async.drainQueues (/Users/lixiansheng/Visual/blog/node_modules/bluebird/js/release/
async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

**Comment by tcrowe** [comment]
Thanks @lzq920 I'll have a look!

**Comment by tcrowe** [comment]
If you see this line and take out `|| 'No Title'` it works: https://github.com/tcrowe/generator-hexo-theme/blob/master/app/templates/layout-nunjucks/category.njk#L10

We can make a PR for this.

The function `list_categories` is making the categories nested which may be wrong too.

<img width="216" alt="screen shot 2017-07-04 at 11 40 08 pm" src="https://user-images.githubusercontent.com/1634015/27850372-63571110-6111-11e7-8854-867fad312a01.png">

<img width="740" alt="screen shot 2017-07-04 at 11 40 15 pm" src="https://user-images.githubusercontent.com/1634015/27850377-6b6b1310-6111-11e7-8acd-99034a8d6743.png">

**Comment by tcrowe** [comment]
Can you try this generator-hexo-theme@0.4.1 and see if it works?

**Comment by lzq920** [comment]
Ok,I can try gennerator-hexo-theme@0.4.1,in the console not error.
But  i have a new question，The tag page article title always is ‘No Title’ and article link is '/'.

**Comment by lzq920** [comment]
Tag page and Category page should  be same

**Comment by lzq920** [comment]
open localhost:4004/tags/   is null
open localhost:4000/categories is null

**Comment by tcrowe** [comment]
Found it: https://github.com/tcrowe/generator-hexo-theme/blob/master/app/templates/layout-nunjucks/tag.njk#L6

`postItem` should be `article`

**Comment by tcrowe** [comment]
That's not fixing it yet but it was wrong too.

**Comment by tcrowe** [comment]
Inside the loop the post object has title but I'm not finding any other properties. Do you know how to fix?

**Comment by lzq920** [comment]
I don't know how to fix it，I was thinking about it！

**Comment by tcrowe** [comment]
Hey @lzq920 I didn't forget just working on some things. If you know how to fix that tag page I will happily take a PR. If not I'll look at it soon and see if I can fix it.

Maybe this theme will give us some tips: https://github.com/jonashao/hexo-theme-pteris/blob/master/layout/tag.njk

**Comment by lzq920** [comment]
I don't know how to add the tagclouds，tag detail is good。
