### ISSUE TITLE
unknown block tag: paginator

### ISSUE THREAD

**Issue by RoamIn** [tcrowe/generator-hexo-theme#16]
After generate theme, start server:

```
Unhandled rejection Template render error: (unknown path) [Line 5, Column 4]
  unknown block tag: paginator
    at Object.exports.prettifyError (D:\Hexo\blog\node_modules\hexo-renderer-njks\node_modules\nunjucks\src\lib.js:34:15)
    at new_cls.render (D:\Hexo\blog\node_modules\hexo-renderer-njks\node_modules\nunjucks\src\environment.js:469:27)
    at new_cls.renderString (D:\Hexo\blog\node_modules\hexo-renderer-njks\node_modules\nunjucks\src\environment.js:327:21)
    at Hexo.renderer (D:\Hexo\blog\node_modules\hexo-renderer-njks\index.js:16:14)
    at Hexo.tryCatcher (D:\Hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\Hexo\blog\node_modules\bluebird\js\release\method.js:15:34)
    at D:\Hexo\blog\node_modules\hexo\lib\hexo\render.js:61:21
    at tryCatcher (D:\Hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Hexo\blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Hexo\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromiseCtx (D:\Hexo\blog\node_modules\bluebird\js\release\promise.js:606:10)
    at Async._drainQueue (D:\Hexo\blog\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (D:\Hexo\blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\Hexo\blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
```

- nunjucks
- scss
- win10
- node v6 or v8

**Comment by tcrowe** [comment]
Thanks @RoamIn some things probably changed between hexo versions for the helpers. We can find out.

Paginator is still in the docs https://hexo.io/docs/helpers.html#paginator

🤔

**Comment by RoamIn** [comment]
I see !
After I saw pug use `!= paginator()` I understand it.
We need to use `{{ paginator() }}`.
Cheers !

**Comment by tcrowe** [comment]
Oh okay. It sounds like you found the problem. Can you link me to the source line please?

Thanks for following up

**Comment by RoamIn** [comment]
- [archive.njk](https://github.com/tcrowe/generator-hexo-theme/blob/a974b4a2a01f4e9988b5ad243210f003f35406b9/app/templates/layout-nunjucks/archive.njk#L79)
- [category.njk](https://github.com/tcrowe/generator-hexo-theme/blob/a974b4a2a01f4e9988b5ad243210f003f35406b9/app/templates/layout-nunjucks/category.njk#L25)
- [index.njk](https://github.com/tcrowe/generator-hexo-theme/blob/a974b4a2a01f4e9988b5ad243210f003f35406b9/app/templates/layout-nunjucks/index.njk#L5)
- [page.njk](https://github.com/tcrowe/generator-hexo-theme/blob/a974b4a2a01f4e9988b5ad243210f003f35406b9/app/templates/layout-nunjucks/page.njk#L9)
- [post.njk](https://github.com/tcrowe/generator-hexo-theme/blob/a974b4a2a01f4e9988b5ad243210f003f35406b9/app/templates/layout-nunjucks/post.njk#L10)
- [tag.njk](https://github.com/tcrowe/generator-hexo-theme/blob/a974b4a2a01f4e9988b5ad243210f003f35406b9/app/templates/layout-nunjucks/tag.njk#L25)

**Comment by RoamIn** [comment]
My pleasure.

**Comment by tcrowe** [comment]
Updated to 0.5.1 with nunjucks fixes https://www.npmjs.com/package/generator-hexo-theme
